on: [push]

jobs:
  ClangFormatCheck:
    runs-on: ubuntu-latest
    name: Clang format check
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clang format check
      run: .github/automation/clang-format.sh
  ci_test_job:
    runs-on: ubuntu-latest
    name: Test for oneDNN
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test action step
      uses: .github/actions/test_action